### ISSUE TITLE
Add gt_answer to last_letter and date.

### ISSUE THREAD

**Issue by Rem1L** [lz1oceani/verify_cot#2]
Dear authors,
I want to make use of your data but the gt_answer in date and last_letter seems not available. While I think you also changed the question format, so I cannot automatically annotate by myself with [date of BIG BENCH](https://github.com/google/BIG-bench/blob/main/bigbench/benchmark_tasks/date_understanding/task.json), could you kindly update it. Thank you.

**Comment by lz1oceani** [comment]
We use the following code to reformat the date dataset.
_ = example of date
noisy_tail = " in MM/DD/YYYY?"
assert _["question"].endswith(noisy_tail), "Question should end with 'in MM/DD/YYYY?'"
_["question"] = _["question"].replace(noisy_tail, "? Please answer in format MM/DD/YYYY.")

For last letters, we use dataset here: https://github.com/kojima-takeshi188/zero_shot_cot/blob/main/dataset/last_letters/last_letters.json .
